kind: pipeline
type: docker
name: Github加速


clone:
  disable: true


trigger:
  event:
    exclude:
      - pull_request


steps:
  - name: 拉代码
    image: dronestock/git
    pull: if-not-exists
    settings:
      verbose: true

  - name: 打包Docker到中央仓库
    image: plugins/docker
    pull: if-not-exists
    when:
      branch:
        - develop
        - master
    settings:
      repo: storezhang/fastgithub
      tags:
        - latest
      compress: true
      mirror: https://mirror.ccs.tencentyun.com
      username: storezhang
      password:
        from_secret: token_docker
